apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "service.name" . }}-analysis-template
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    app: {{ include "service.name" . }}
    app.kubernetes.io/version: "1.0.0"
spec:
  metrics:
  - name: {{ include "service.name" . }}-prometheus-metric
    interval: 10s
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: https://internal:XXXXXXXXXXXX@prometheus.istio-system.svc.cluster.local:9090
        query: |
                    sum(irate( istio_requests_total{reporter="source",destination_service_name=~"dstrategies-back",response_code!~"5.*"}[30s] )) / sum(irate( istio_requests_total{reporter="source",destination_service_name=~"dstrategies-back"}[30s] ))
